# Generated by Django 4.1.1 on 2022-09-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.TextField(null=True),
        ),
    ]
