# Generated by Django 4.1.1 on 2022-09-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_alter_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipetag',
            name='icon',
            field=models.TextField(null=True),
        ),
    ]
