# Generated by Django 4.1.1 on 2022-09-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_recipetag_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='materialList',
            field=models.ManyToManyField(blank=True, null=True, to='recipe.material'),
        ),
    ]
