# Generated by Django 4.1.1 on 2022-09-25 23:36

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_alter_recipe_materiallist'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='title', unique_with=('created', 'company')),
        ),
    ]
